/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISupportsInterface } from "./ISupportsInterface";
export type { SupportsInterface } from "./SupportsInterface";
