/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISupportsInterface__factory } from "./ISupportsInterface__factory";
export { SupportsInterface__factory } from "./SupportsInterface__factory";
